# Découpage d'une chaine de caratère (Slicing)
college = "College bois de boulogne "
print(college[0])
print(college[8])
print(college[21])
print(college[-1])
print(college[-2])
print(college[8: 12])
print(college[16: 24])
print(college[-9: -1])
print(college[0:21:3])
print(len(college))
print(college[:])
print(college[::])
print(college[::-1])